import type { Metadata } from "next";
import "./globals.css";
import LayoutContent from "./LayoutContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
