import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import AppSidebar from "@/components/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="bg-white"
       >
        <Header/>
        <main className="flex">


          <AppSidebar/>

          <div className="flex-1 m-1 bg-gray-100">
            
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
