import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Default icon
    shortcut: "/favicon-32x32.png", // Browser shortcuts
    apple: "/apple-touch-icon.png", // Apple devices
    other: [
      {
        rel: "manifest",
        url: "./public/site.webmanifest", // Optional for PWA
      },
    ],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Header/>
        <main className="flex p-2 min-h-screen">
        <Sidebar/>
        <div className="flex-1 bg-gray-200 p-2">

        {children}
        </div>
        </main>
      </body>
    </html>
  );
}
